const lyricsData = {
    "shut down": "BLACKPINK in your area, eh-oh <br> BLACKPINK in your area, eh-oh <br> <br> Kombaegi anya ttonan jok opsseunikka <br> Gogaedeuri dora jinjonghae mok kkokkilra <br> Bunhongppiche oreum drip, drip, drip, freeze 'em on sight <br> Shut it down, what, what, what, what? <br> Kkeimi anya jin jogi opsseunikka <br> Jijobwa ne moge mokjjureun nae gonikka <br> Ttangppadage daeun pedal we go two zero five <br> Shut it down, uh-uh, uh-uh <br> <br> Chorok bireul naeryo mori wiro, don't trip, baby <br> Gyomsonhage geunyang anjaisso, just sit, baby <br> Praying for my downfall, many have tried, baby <br> Catch me when you hear my Lamborghini go vroom, vroom, vroom, vroom <br> <br> When we pull up, you know it's a shutdown <br> Ganpan naerigo mun jamga shut down <br> Whip it, whip it, whip it, whip it <br> Whip it, whip it, whip it, whip it <br>  It's black and it's pink once the sun down <br> When we pull up, you know it's a shutdown <br>  Ganpan naerigo mun jamga shut down <br> Whip it, whip it, whip it, whip it <br> Whip it, whip it, whip it, whip it <br> Keep watching mе shut it down <br> <br> Nah, you don't wanna be on my bad side <br> That's right, I'm slidin' through <br> Bunch of wannabes that wanna bе me <br> Me three if I was you <br> Been around the world, pearls on ya girl <br> VVS's we invested, uh <br> Need a lesson, see the necklace, see these dresses <br> We don't buy it, we request it, uh <br> A rock star, a pop star, but rowdier <br> Say bye to the paparazzi, get my good side, I'll smile for ya <br> Know it ain't fair to ya, it's scarin' ya like what now <br> BLACKPINK in your area, the area been shut down <br> It's a shutdown <br> <br> Ne daeum dabanjiya ttokpparo bwa, don't sleep, baby <br> Dwijibobwa igon gagyokpyoya, ain't cheap, baby <br> Stay in your own lane 'cause I'm 'bout to swerve <br> Catch me when you hear my Lamborghini go vroom, vroom, vroom, vroom <br> <br> When we pull up, you know it's a shutdown <br> Ganpan naerigo mun jamga shut down <br> Whip it, whip it, whip it, whip it <br> Whip it, whip it, whip it, whip it <br> It's black and it's pink once the sun down <br> When we pull up, you know it's a shutdown <br> Ganpan naerigo mun jamga shut down <br> Whip it, whip it, whip it, whip it <br> Whip it, whip it, whip it, whip it <br> Keep watching me shut it down <br> <br> Shut it down (Eh-oh), BLACKPINK in your area <br> Shut it down (Eh-oh), woah, woah, woah, woah <br> Shut it down (Eh-oh), BLACKPINK in your area <br> Keep talkin', we shut you down",


    "Boombayah": "(Hot) BLACKPINK in your area<br> (Hot) BLACKPINK in your area<br> Been a bad girl, I know I am<br> And I'm so hot, I need a fan<br> I don't want a boy, I need a man<br><br> Click-clack Badda bing badda boom<br> Muneul bakchamyeon modu nal barabom<br> Gudi aesseo noryeok an haedo<br> Modeun namjadeureun kopiga pangpangpang<br> Pangpang parapara pangpangpang<br> Jigeum nal wihan chukbaereul jjanjjanjjan<br> Hands up nae sonen bottle full o' Henny<br> Nega malloman deuddeon gyaega naya Jennie<br><br> Chumchuneun bulbicheun nal gamssago done<br> Black to the pink eodiseodeun teukbyeolhae (Oh yes)<br> Chyeoda bodeun maldeun I wanna dance<br> Like ttaradaradanttan<br> Ttaradaradanttan, ttudurubbau<br><br> Joha i bunwigiga joha<br> Joha nan jigeum nega joha<br> Jeongmal banhaesseo oneul bam<br> Neowa chumchugo sipeo<br><br> Boombayah<br> Yah yah yah, boombayah<br> Yah yah yah, boombayah<br> Yah yah yah yah<br> Boom-boom-ba, boom-boom-ba (Oppa!)<br> Yah, yah yah, yah yah yah yah, yah yah yah<br> Yah, yah yah, yah yah yah yah, yah yah yah (Oppa!)<br> Yah, yah yah, yah yah yah yah, yah yah yah<br> Yah, yah yah, yah yah yah, boom-boom-ba, boombayah<br><br> (Hot) BLACKPINK in your area<br> Uh, ije dallyeoyaji mwol eotteokhae<br> Nan cheol eobseo geob eobseo Man<br> Middle finger up, F-U pay me<br> 90's baby, I pump up the jam<br> Dallyeobwa dallyeobwa oppaya Lambo<br> Oneuleun neowa na jeolmeumeul Gamble<br> Gamhi nal makjima hoksina nuga nal makado<br> I'mma go, brrrr, Rambo<br> Ne soni nae heorireul gamssago done<br> Front to my back Nae mommaeneun teukbyeolhae (Oh yes)<br> Ne nunbicheun I know you wanna touch<br> Like touch, touch, to-to-touch<br> Ttudurubbau<br>    Joha i bunwigiga joha<br> Joha nan jigeum nega joha<br> Jeongmal meosisseo oneul bam<br> Neowa chumchugo sipeo<br><br> Boombayah<br> Yah yah yah, boombayah<br> Yah yah yah, boombayah<br> Yah yah yah yah<br> Boom-boom-ba, boom-boom-ba (Oppa!)<br> Yah, yah yah, yah yah yah yah, yah yah yah<br> Yah, yah yah, yah yah yah yah, yah yah yah (Oppa!)<br> Yah, yah yah, yah yah yah yah, yah yah yah<br> Yah, yah yah, yah yah yah, boom-boom-ba, boombayah <br><br> Oneuleun maen jeongsin ttawin beorigo<br> Haneuleul neomeoseo olla gal geoya<br> Kkeuteul moreuge ppalli dalligo sipeo<br> Let's go (Ooh-ooh)<br> Let's go (Ooh-ooh)<br> <br> Oneuleun maen jeongsin ttawin beorigo<br> Haneuleul neomeoseo olla gal geoya<br> Kkeuteul moreuge ppalli dalligo sipeo<br> Let's go (Ooh-ooh)<br> Let's go (Ooh-ooh)",


    
    "Whistle":"Hey, boy<br> <br> Make 'em whistle like a missile bomb, bomb<br> Every time I show up, blow up, uh<br> Make 'em whistle like a missile bomb, bomb<br> Every time I show up, blow up, uh<br><br> Neon neomu areumdawo<br> Neol ijeul suga eobseo<br> Geu nunbichi ajik nareul<br> Ireohge seollege hae, boom, boom<br> Twenty four/three six five ojik neowa gachi hagopa<br> Najedo i bamedo<br> Ireohge neoreul wonhae, hmm, hmm<br><br> Yeah, modeun namjadeuli nal maeil check out<br> Daebubuninal gajilsu itda chakgak<br> Jeoldae manheungeol wonchianha mameul wonhae nan (Uh)<br> Neon simjangeul doryeonae boyeobwa<br> Aju ssikssikhage ttaeron chic, chic hage<br> So hot, so hot naega eojjeol jul moleugehae (Uh)<br> Najimaki bulleojwo<br> Nae gwitgae doneun hwiparamcheoreom<br><br> Idaelo jinachiji mayo<br> Neodo nacheoleom nal ijeul suga eobsdamyeon, whoa-oh-oh<br> Neol hyanghani maeumeun Fire<br> Nae simjangi ppareuge ttwijanha<br> Jeomjeom gakkai deullijanha<br><br> Hwiparam (Uh)<br> Hwiparam-param-param<br> (Can you hear that?)<br> Hwipara-para-para-ram<br> Hwiparam (Uh)<br> Hwiparam-param-param<br> (Can you hear that?)<br> Hwipara-para-para-ram<br><br> (Hold up) Amu mal haji ma <br> Just whistle to my heart <br> Geu soriga jigeum nareul <br> Ireohge seollege hae, boom, boom <br> Saenggakeun jiruhae <br> Neukkimi, shh<br> Every day, all day<br> Nae gyeoteman issejwo, zoom, zoom<br><br> Uh, eonjena nan stylin'<br> Dodohajiman ne apeseon darlin'<br> Tteugeowojijanha like a desert island<br> Neo alagalsurok ullyeodaeneun maeumsok<br> Geuman naeppae neomeowala naege boy<br> Ijen checkmate geimeun naega win (Uh-huh)<br> Nan neol taeghae anajwo deo sege nuga<br> Neol galochae gagi jeone naega uh<br><br> Idaelo jinachiji mayo<br> Neodo nacheoleom nal ijeul suga eobsdamyeon, whoa-oh-oh<br> Neol hyanghani maeumeun Fire<br> Nae simjangi ppareuge ttwijanha<br> Jeomjeom gakkai deullijanha<br><br> Hwiparam (Uh)<br> Hwiparam-param-param<br> (Can you hear that?)<br> Hwipara-para-para-ram<br> Hwiparam (Uh)<br> Hwiparam-param-param<br> (Can you hear that?)<br> Hwipara-para-para-ram<br><br> This beat got me feeling like<br> Baramcheoreom seuchyeoganeun<br> Heunhan inyeoni anigil<br> Manheun maleun pilyo eobseo<br> Jigeum neoui gyeote<br> Nareul deryeoga jwo<br> Ooh-ooh-ooh, ooh-ooh-ooh, ooh<br><br> Make 'em whistle like a missile bomb, bomb<br> Every time I show up, blow up, uh<br> Make 'em whistle like a missile bomb, bomb<br> Every time I show up, blow up, uh",


    "Playing with Fire":"Uri eomman maeil naege malhaesseo<br> Eonjena namja joshimharago<br> Sarangeun machi buljangnan gataseo<br> Dachinikka, eh<br> Eomma mari kkok majeuljjido molla<br> Neol bomyeon nae mami tteugeopge daraolla<br> Duryeoumbodan neol hyanghan kkeullimi<br> Deo keunikka, eh<br><br> Meomchul su eomneun i tteollimeun, on and on and on<br> Nae jeonbureul neoran sesange da deonjigo shipeo<br> Look at me, look at me now, ireoke neon nal aetaeugo itjana<br> Kkeul su eopseo<br><br> Uri sarangeun buljangnan<br> (Oh-oh, oh-oh)<br> My love is on fire (Ooh)<br> Now burn, baby, burn<br> Buljangnan<br> (Oh-oh, oh-oh)<br> My love is on fire (Ooh)<br> So don't play with me, boy<br> Buljangnan<br><br> Oh no, nan imi meolli abeoryeonneungeol<br> Eoneusae i modeun ge jangnani anin geol<br> Sarangiran ppalgan bulsshi<br> Bureora baram deo keojeoganeun bulkkil<br> Ige yaginji doginji uri eommado molla<br> Nae mam doduginde wae gyeongchaldo molla<br>Bul buteun nae shimjange deo bueora neoran gireum<br> Kiss him, will I diss him?<br> I don't know, but I miss him <br> Jungdogeul neomeoseon i sarangeun crack<br> Nae shimjange saekkareun black, ah!<br><br> Meomchul su eomneun i tteollimeun, on and on and on<br> Nae jeonbureul neoran bulkkil sogeuro deonjigo shipeo<br> Look at me, look at me now, ireoke neon nal aetaeugo itjana<br> Kkeul su eopseo<br> Uri sarangeun buljangnan<br> (Oh-oh, oh-oh)<br> My love is on fire (Ooh)<br> Now burn, baby, burn<br> Buljangnan<br> (Oh-oh, oh-oh)<br> My love is on fire (Ooh)<br> So don't play with me, boy<br> Buljangnan<br><br> Geotjabeul suga eomneun geol<br> Neomuna ppalli peojeo ganeun i bulkkil<br> Ireon nal meomchuji ma<br> I sarangi oneul bameul taeweobeorige<br> Ooh-ooh<br>",


    "Stay":"Tukamyeon geochin maldeullo nae mame sangcheoreul naenoko<br> Mianhadan mal hanmadi eopsi tto na honja wirohago<br> Oneul harudo hoksi nal tteonalkka neul buranhae hae<br> I just want you to stay<br> Jeomjeom mudyeojyeo ganeun neoui geu mupyojeong soge, oh-oh<br> Cheoncheonhi naeryeonochamyeo geoure soksagigon hae, whoa-oh<br> Nal dangyeonhage saenggakaneun neojiman geuge neodawo<br> Geuraedo stay, stay, stay with me<br> Neol daleun deuthan seulpeun melody (Ah-ah-ah-ah)<br> Ireoke nal ullineunde, eh-eh<br> Ne hyanggineun dalkomhan felony (Ah-ah-ah-ah)<br> Neomu mipjiman saranghae<br> Eoduun bami nal gadugi jeone nae gyeoteul tteonajima<br> Ajik nal saranghani nae mamgwa gatdamyeon oneureun tteonajima<br> Guji neoyeoyaman haneun iyuneun mutjima<br> Geujeo nae gyeote stay with me<br> It goes a little something like<br> La-la-la-la-la-la, la-la-la-la-la-la, la-la-la-la-la-la<br> La-la-la-la-la-la, la-la-la-la-la-la, la-la-la-la-la-la<br> Jigeum dangjang maneungeol baraneun ge anya<br> Geujeo nae gyeote stay with me<br><br> Sasireun nan deo baraneun ge eopseo ije<br> Simjangeun ttwigin haneun geonji mugamgakae geurae<br> Saramdeulgwaui eokjiseureon hanmadibodan<br> Neowaui eosaekan chimmugi charari joa<br> So stay geuge eodiga dwaetgeon mariya<br> Gakkeum eodumi ol ttaemyeon I'll be your fire<br> Geojit gateun sesang sok yuilhan truth, it's you<br> This a letter from me to you<br><br> Neol daleun deuthan seulpeun melody (Ah-ah-ah-ah)<br> Ireoke nal ullineunde, eh-eh<br> Ne hyanggineun dalkomhan felony (Ah-ah-ah-ah)<br> Neomu mipjiman saranghae<br><br>    Eoduun bami nal gadugi jeone nae gyeoteul tteonajima<br> Ajik nal saranghani nae mamgwa gatdamyeon oneureun tteonajima<br> Guji neoyeoyaman haneun iyuneun mutjima<br> Geujeo nae gyeote stay with me<br> It goes a little something like<br> La-la-la-la-la-la, la-la-la-la-la-la, la-la-la-la-la-la<br> La-la-la-la-la-la, la-la-la-la-la-la, la-la-la-la-la-la<br> Jigeum dangjang maneungeol baraneun ge anya<br> Geujeo nae gyeote stay with me<br> It goes a little something like<br> La-la-la-la-la-la, la-la-la-la-la-la, la-la-la-la-la-la<br> La-la-la-la-la-la, la-la-la-la-la-la, la-la-la-la-la-la<br> *jigeum dangjang maneungeol baraneun ge anya<br> Geujeo nae gyeote stay with me*",


    "As If It's Your Last":"(Little bit of that) <br> (Little bit of this)<br> (Little bit of that)<br> (Gimme, gimme, gimme)<br><br> (Gimme little bit of that) Neo mwonde jakku saenggangna<br>(Gimme little bit of this) Jajonsim sanghae aega ta<br> Eolguri tteugeopgo gaseumeun gyesok ttwieo<br> Nae momi mamdaero an dwae eojireowo<br> (Gimme little bit of that) Neon han jumui morae gata<br> (Gimme little bit of this) Japil deut japiji ana<br> Neon swipji aneun geol geuraeseo deo kkeullyeo<br> Nae mami mamdaero an dwae eoieopseo<br><br> Jigeum neoreul wonhaneun nae<br> Sumgyeori neukkyeojini<br> Neol barabogo isseodo missing you<br> Seotun nal won't you set me free-e-e-e?<br><br> Baby, nal teojil geotcheoreom anajwo<br> Geuman saenggakae mwoga geuri eoryeowo<br> Geojinmalcheoreom kiss-haejwo naega neoege<br> Majimak sarangin geotcheoreom<br> Majimakcheoreom (Yeah) ma-ma-majimakcheoreom (Yeah)<br> Majimak bamin geotcheoreom love<br> Majimakcheoreom (Yeah) ma-ma-majimakcheoreom (Yeah)<br> Naeil ttawin eomneun geotcheoreom love<br><br> Uh, I'ma fall in love, baby<br> You gon' finna catch me, uh<br> Give you all of this, baby<br> Call me pretty and nasty<br> 'Cause we gonna get it, my love<br> You can bet it on black<br> We gon' double the stack on them, woo<br> I be the Bonnie and you be my Clyde<br> We ride or die, Xs and Os<br><br> Siganeun heulleoganeunde<br> Maeumman geupaejiji<br> Nae sesangeun neo hanaman missing you<br> Seotun nal won't you set me free-e-e-e?<br><br> Baby, nal teojil geotcheoreom anajwo<br> Geuman saenggakae mwoga geuri eoryeowo<br> Geojinmalcheoreom kiss-haejwo naega neoege<br> Majimak sarangin geotcheoreom<br> Majimakcheoreom (Yeah) ma-ma-majimakcheoreom (Yeah)<br> Majimak bamin geotcheoreom love<br> Majimakcheoreom (Yeah) ma-ma-majimakcheoreom (Yeah)<br> Naeil ttawin eomneun geotcheoreom love<br><br> One, two, three saeroun, sijagi, ya<br> Jeoldae dwidorabojin aneul geonikka<br> Nal neoege deonjimyeon neoneun nal kkok jabajwo<br> Sesangeun uril kkeokji mothal tenikka<br> BLACKPINK in your area<br> (BLACKPINK in your—)<br><br> Baby, nal teojil geotcheoreom anajwo<br> Geuman saenggakae mwoga geuri eoryeowo<br> Geojinmalcheoreom kiss-haejwo naega neoege<br> Majimak sarangin geotcheoreom<br> Majimakcheoreom (Yeah) ma-ma-majimakcheoreom (Yeah)<br> Majimak bamin geotcheoreom love<br> Majimakcheoreom (Yeah) ma-ma-majimakcheoreom (Yeah)<br> Naeil ttawin eomneun geotcheoreom love",


    "Pink Venom":"Pink Venom...",
    "how you like that": "How you like that lyrics...",

};

function search() {
    const searchTerm = document.getElementById("search-bar").value.toLowerCase(); // Convert the search term to lowercase
    const content = document.getElementById("content");

    // Check if the search term exists in the lyrics data (case-insensitive)
    for (const key in lyricsData) {
        if (key.toLowerCase() === searchTerm) {
            const lyrics = lyricsData[key];

            // Display the lyrics in the content area
            content.innerHTML = `
                <h2>${key} Lyrics:</h2>
                <p>${lyrics}</p>
            `;
            return; // Exit the loop once a match is found
        }
    }

    content.innerHTML = "<p>Lyrics not found.</p>";
}
